version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: cuenta-postgres
    environment:
      POSTGRES_DB: mibasedatos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./basedatos.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cuenta_user -d mibasedatos"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cuenta-network

  # Aplicaci√≥n Spring Boot
  cuenta-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cuenta-application
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mibasedatos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "1234"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cuenta-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  cuenta-network:
    driver: bridge
    name: cuenta-network
    external:false

